apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sre
  name: xxl-job-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxl-job-admin
  template:
    metadata:
      labels:
        app: xxl-job-admin
    spec:
      containers:
        - name: xxl-job-admin
          image: xuxueli/xxl-job-admin:2.3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PARAMS   # 定义变量，用来接收sql的用户/密码 mysql为k8s集群内的service名称，在k8s集群内部可以直接使用service名称，因为集群默认做了coredns解析
              value: "--spring.datasource.url=jdbc:mysql://xxl-db:3306/xxl_job?allowPublicKeyRetrieval=true&Unicode=true&characterEncoding=UTF-8&useSSL=false --spring.datasource.username=maurice --spring.datasource.password=martha --spring.mail.username=morse2work@gmail.com --spring.mail.password=flyaway"
---
apiVersion: v1
kind: Service
metadata:
  namespace: sre
  name: xxl-job-admin
  labels:
    app: xxl-job-admin
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: xxl-job-admin