# Dockerfile for apollo-adminservice
# 1. ./scripts/build.sh
# 2. Build with: mvn docker:build -pl apollo-adminservice
# 3. Run with: docker run -p 8090:8090 -e SPRING_DATASOURCE_URL="jdbc:mysql://host.docker.internal:3306/ApolloConfigDB?characterEncoding=utf8" -e SPRING_DATASOURCE_USERNAME=maurice -e SPRING_DATASOURCE_PASSWORD=martha__ -d -v /tmp/logs:/opt/logs --name apollo-adminservice apolloconfig/apollo-adminservice

#FROM openjdk:8-jre-alpine
FROM openjdk:11.0.9.1-jre-buster
MAINTAINER dinghesheng

ENV APOLLO_RUN_MODE "Docker"
ENV VERSION 2.0.1
ENV SERVER_PORT 8090

RUN   apt install  unzip curl bash tzdata \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone

ADD apollo-adminservice-${VERSION}-github.zip /apollo-adminservice/apollo-adminservice-${VERSION}-github.zip

RUN unzip /apollo-adminservice/apollo-adminservice-${VERSION}-github.zip -d /apollo-adminservice \
    && rm -rf /apollo-adminservice/apollo-adminservice-${VERSION}-github.zip \
    && chmod +x /apollo-adminservice/scripts/startup.sh

EXPOSE $SERVER_PORT

CMD ["/apollo-adminservice/scripts/startup.sh"]
