kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: sre
  name: spring-app-initdb-pv-claim
  labels:
    app: spring-app-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  namespace: sre
  name: spring-app-db
  labels:
    app: spring-app-db
spec:
  ports:
    - port: 3306
  selector:
    app: spring-app-db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sre
  name: spring-app-db
spec:
  selector:
    matchLabels:
      app: spring-app-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spring-app-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: martha
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-sql
          configMap:
            name: spring-app-init-sql

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: sre
  name: spring-app-init-sql
data:
  initdb.sql: |
    CREATE USER 'maurice'@'%' IDENTIFIED BY 'martha';
    GRANT ALL PRIVILEGES ON *.* TO 'maurice'@'%' WITH GRANT OPTION;
    flush privileges;
    CREATE database alpha;
    use alpha;
    DROP TABLE IF EXISTS `user`;
    
    CREATE TABLE user(
      id bigint primary key,
      name varchar(255) not null default ''
    );

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-svc
  namespace: sre
spec:
  selector:
    app: spring-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: sre
spec:
  selector:
    matchLabels:
      app: spring-app
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: bugfans/spring-app:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://spring-app-db:3306/alpha
            - name: SPRING_DATASOURCE_USERNAME
              value: maurice
            - name: SPRING_DATASOURCE_PASSWORD
              value: martha
            - name: XXL_JOB_ADMIN_ADDRESS
              value: 'http://xxl-job-admin:8080'
            - name: APOLLO_META
              value: 'http://service-apollo-meta-server-dev:8080'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080